### ISSUE TITLE
review language files

### ISSUE THREAD

**Issue by tuurma** [eeditiones/eltec#2]
in [resources/i18n/app](https://github.com/eeditiones/eltec/tree/main/resources/i18n/app)

**Comment by lb42** [comment]
The English is fine and I trust you for the Polish. I have asked around for the other languages.

**Comment by lb42** [comment]
Added two new languages (serbian and spanish). The former is available either in cyrillic or in roman letters;  I chose the latter.

**Comment by tuurma** [comment]
There are a few labels not showing correctly, do not despair, this will fix itself when we merge newly translated Publisher labels (estimated in about 1w)

![image](https://user-images.githubusercontent.com/449468/101991723-d591a480-3cae-11eb-9028-506954f0fc08.png)
