### ISSUE TITLE
cant select multiple facet values

### ISSUE THREAD

**Issue by lb42** [eeditiones/eltec#3]
it doesnt seem possible to make multiple selections from a given facet. consequently you cannot search for texts which appear in more than one timeslot, or more than one language. This is a problem, especially since "english" appears twice in the list of languages, once for level0 and once for level1 encodings (I think).

**Comment by tuurma** [comment]
English appears twice due to inconsistency in attribute values for TEI/@xml:lang (`eng` and `ENG`, respectively). I think that there is only one value per document for TEI/@xml:lang , multiple values are available in profileDesc/langUsage

Multiple selection for facets is supported server-side but lacks support in UI. There is a relevant issue in Publisher tracker, currently in need of funding https://github.com/eeditiones/tei-publisher-app/issues/33

**Comment by tuurma** [comment]
Sorry, `en` (correct) and 13 cases of `ENG` (incorrect). Spanish use `SPA` instead of `es`.

**Comment by tuurma** [comment]
Adding manually the other facet value to the URL would present correct data set, just UI is wrong

![image](https://user-images.githubusercontent.com/449468/97724162-e0142800-1acc-11eb-8a04-7513980eb270.png)

**Comment by tuurma** [comment]
after the fix correcting display of selected facets

![image](https://user-images.githubusercontent.com/449468/97724882-ca533280-1acd-11eb-9d5d-64e2e2867332.png)

**Comment by lb42** [comment]
Thanks for spotting this inconsistency in time for the next release: I am correcting the data in github right now.

**Comment by lb42** [comment]
ELTeC-en data is now correct. Leaving this ticket open to remind me to fix SPA, but also because selection by multiple facet values is a real requirement for this project. Another example: selecting texts from timeslots before/after 1870. How much funding does it need? If the server already supports this, it can't be that hard!

**Comment by tuurma** [comment]
Ha, common misconception. Server-side stuff is usually 10-20% of the time, user interface is pain and misery ;-)

I'd estimate 1 day. Needs to be configurable between current behaviour and only sending the request after choosing facets by some kind of Apply/Submit button.

**Comment by tuurma** [comment]
Fixed. Not sure I like it - one needs to go down the list of facets to press the SUBMIT button now

![image](https://user-images.githubusercontent.com/449468/101991683-982d1700-3cae-11eb-8218-9a2e79981843.png)
