### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by lb42** [eeditiones/eltec#4]
Sort by title or author sorts all unaccented characters ahead of all accented letters, which is confusing. Is it sorting by unicode code values or what? See https://en.wikipedia.org/wiki/European_ordering_rules

**Comment by tuurma** [comment]
Set the collation method to `http://www.w3.org/2013/collation/UCA` which probably does what one expects

![image](https://user-images.githubusercontent.com/449468/97727643-f15f3380-1ad0-11eb-8b54-c8707b3c95c8.png)

**Comment by tuurma** [comment]
closed with https://github.com/eeditiones/eltec/commit/d36bbd8db2339cd4ce3b0af789feef2a1f99ac36
