### ISSUE TITLE
Show top 50 ???

### ISSUE THREAD

**Issue by lb42** [eeditiones/eltec#8]
What is this omnipresent check box for? It doesn't seem to do anything. How do I make it go away?

**Comment by tuurma** [comment]
True, it only makes sense where facets returned are more numerous then default displayed, not the case for ELTeC

**Comment by tuurma** [comment]
Now only shows when number of available facet options is greater than max number configured for this facet dimension

**Comment by lb42** [comment]
A distinct improvement. Maybe the wording should be changed too? How about just "Show more values ..."
