### ISSUE TITLE
facetted search of search results not working

### ISSUE THREAD

**Issue by lb42** [eeditiones/eltec#9]
when i look at the results of a word search, a facet search window opens on the right of the display which i assume is meant to allow me to further refine the search by the available facets. but only language (which I can select multiple values for here btw) seems to reduce the display; selecting any checkbox for the other facets has no effect

**Comment by tuurma** [comment]
Can't reproduce so far

searching for e.g. par* I'm getting a 1000 matches, drilling down by e.g. of the periods seems to work as expected

NB: you can only select multiple facets if you manage to select different checkboxes before request results are returned, it's not 'really' working. It 'works' this way on main page too, probably just works faster so more difficult to spot.

![image](https://user-images.githubusercontent.com/449468/100100814-ac28ea00-2e61-11eb-8d9c-2be6a557615e.png)

![image](https://user-images.githubusercontent.com/449468/100100912-d084c680-2e61-11eb-8bc4-6946961f8629.png)
